### PR TITLE
 Added worker Assignment and add More Submission type

### PR DESCRIPTION
**Pull request by mr8bit**
- Added more types for uploading Jupyter Notebook, Python Code, Power Point, DrawIO
- Implemented sending submission with Text and URL

### CODE REVIEW

**Comment by mr8bit** [comment]
https://github.com/frappe/lms/issues/714

**Comment by pateljannat** [comment]
@mr8bit can you please fix the linters?

**Comment by mr8bit** [comment]
@pateljannat Ok, I'll fix it soon

**Comment by pateljannat** [comment]
@mr8bit This version of the app will soon be replaced by a new version which is currently the develop branch of the app. The new version is significantly different. The frontend code is written in VueJs and the UI has also changed a lot. Would you be interested in contributing this feature in the new version instead of here as we don't want to add new features to the old version anymore?

**Pull request closed without merging**
